name: QR Code Generator

on:
  push:
    paths:
      - 'decks/**/*.yaml'
      - 'decks/**/questions/**/*.yaml'
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcode[pil]
          
      - name: Generate QR codes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # For manual triggers, process all question files
            find decks -name "*-question.md" | while read -r file; do
              DECK_NAME=$(echo $file | cut -d'/' -f2)
              QUESTION_ID=$(echo $file | cut -d'/' -f4 | sed 's/-question.md//')
              
              python -c "
              from src.qr_generator import generate_question_qr_code
              generate_question_qr_code('$DECK_NAME', '$QUESTION_ID')
              "
            done
          else
            # For push events, only process changed files
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "decks/.*/questions/.*-question.md")
            
            for file in $CHANGED_FILES; do
              DECK_NAME=$(echo $file | cut -d'/' -f2)
              QUESTION_ID=$(echo $file | cut -d'/' -f4 | sed 's/-question.md//')
              
              python -c "
              from src.qr_generator import generate_question_qr_code
              generate_question_qr_code('$DECK_NAME', '$QUESTION_ID')
              "
            done
          fi
          
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add decks/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate QR codes for ${{ github.event_name == 'workflow_dispatch' && 'all questions' || 'changed questions' }}" && git push) 