name: Integration Test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/integration-test.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/integration-test.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install
          
      - name: Create test question
        run: |
          mkdir -p integration-test/questions
          printf '%s\n' '# Quiz Questions' \
            '' \
            '## Test Integration Question' \
            '' \
            '1. Option One' \
            '2. Option Two' \
            '3. Option Three (TRUE)' \
            '4. Option Four' \
            '5. Option Five (TRUE)' \
            '6. Option Six' \
            '7. Option Seven' \
            '8. Option Eight' \
            '9. Option Nine' \
            '10. Option Ten' > integration-test/questions/test-question.md
          
      - name: Create test QR code
        run: |
          poetry install
          cd integration-test/questions
          printf '%s\n' 'import qrcode' \
            'qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=4)' \
            "qr.add_data('https://example.com/integration-test')" \
            'qr.make(fit=True)' \
            "img = qr.make_image(fill_color='black', back_color='white')" \
            "img.save('test-qr.png')" | poetry run python3
          
      - name: Generate Quiz
        run: |
          poetry run python -m src.svg_generator.generator ../integration-test/questions/test-question.md ../integration-test/questions/test-output.pdf
          
      - name: Verify PDF was created
        run: |
          if [ ! -f integration-test/questions/test-output.pdf ]; then
            echo "PDF file was not created!"
            exit 1
          fi
          
          # Check PDF size is reasonable (more than 1KB)
          FILE_SIZE=$(du -k integration-test/questions/test-output.pdf | cut -f1)
          if [ "$FILE_SIZE" -lt 1 ]; then
            echo "PDF file is too small (likely empty)"
            exit 1
          fi
          
          echo "Integration test passed successfully!"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-output
          path: |
            integration-test/questions/test-question.md
            integration-test/questions/test-qr.png
            integration-test/questions/test-output.pdf