name: Integration Test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'decks/**'
      - 'scripts/**'
      - '.github/workflows/integration-test.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'decks/**'
      - 'scripts/**'
      - '.github/workflows/integration-test.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install
          
      - name: Install poppler-utils (for pdftotext)
        run: |
          sudo apt-get update && sudo apt-get install -y poppler-utils
          
      - name: Run integration test
        run: |
          chmod +x scripts/test_integration.sh
          ./scripts/test_integration.sh
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-output
          path: /tmp/integration-test/output/