name: QR Code Generator

on:
  push:
    paths:
      - 'decks/**/*.yaml'
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcode[pil]
          
      - name: Generate QR codes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # For manual triggers, process all question files
            find decks -name "*-question.md" | while read -r file; do
              DECK_NAME=$(echo $file | cut -d'/' -f2)
              QUESTION_ID=$(echo $file | cut -d'/' -f4 | sed 's/-question.md//')
              
              python -c "
              from src.qr_generator import generate_question_qr_code
              generate_question_qr_code('$DECK_NAME', '$QUESTION_ID', output_dir='gh-pages/decks')
              "
            done
          else
            # For push events, only process changed files
            # Check if we have a valid before commit
            if git rev-parse --verify --quiet ${{ github.event.before }} >/dev/null; then
              CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "decks/.*/questions/.*-question.md")
            else
              # If no before commit, get all files in the current commit
              CHANGED_FILES=$(git ls-tree -r --name-only ${{ github.sha }} | grep "decks/.*/questions/.*-question.md")
            fi
            
            if [ -n "$CHANGED_FILES" ]; then
              for file in $CHANGED_FILES; do
                DECK_NAME=$(echo $file | cut -d'/' -f2)
                QUESTION_ID=$(echo $file | cut -d'/' -f4 | sed 's/-question.md//')
                
                python -c "
                from src.qr_generator import generate_question_qr_code
                generate_question_qr_code('$DECK_NAME', '$QUESTION_ID', output_dir='gh-pages/decks')
                "
              done
            else
              echo "No question files to process"
            fi
          fi
          
      - name: Commit and push if changes
        run: |
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add decks/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate QR codes for ${{ github.event_name == 'workflow_dispatch' && 'all questions' || 'changed questions' }}" && git push origin gh-pages) 