name: QR Code Generator

on:
  push:
    paths:
      - 'decks/**/*.yaml'
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branches
        uses: ./.github/actions/checkout-branches
      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: '3.11'
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Generate QR codes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ./scripts/generate_qr_codes.sh "gh-pages/decks"
          else
            ./scripts/generate_qr_codes.sh "gh-pages/decks/${{ github.event.inputs.deck_name }}"
          fi
      - name: Commit and push if changes
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: "Generate QR codes"
          user-name: "maoo"
          user-email: "maoo@apache.org"