name: QR Code Generator

on:
  push:
    paths:
      - 'decks/**/*.yaml'
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install
          
      - name: Generate QR codes
        run: |
          chmod +x scripts/generate_qr_codes.sh
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # For manual triggers, process all decks
            ./scripts/generate_qr_codes.sh manual
          else
            # For push events, process changed files
            ./scripts/generate_qr_codes.sh push "${{ github.event.before }}" "${{ github.sha }}"
          fi
          
      - name: Commit and push if changes
        run: |
          cd gh-pages
          git config --local user.email "maoo@apache.org"
          git config --local user.name "maoo"
          git add decks/*
          git commit -m "Generate QR codes" || exit 0
          git push origin gh-pages