name: Convert SVG to PDF

on:
  push:
    paths:
      - 'decks/**/*.svg'
  workflow_dispatch:
    inputs:
      deck_name:
        description: 'Name of the deck to process (e.g., "deck1"). Leave empty to process all decks.'
        required: false
        type: string

jobs:
  convert-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get files to process
        id: files-to-process
        if: github.event_name == 'push'
        uses: tj-actions/changed-files@v46
        with:
          files: |
            decks/**/*.svg

      - name: Set files to process for manual run
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ -n "${{ github.event.inputs.deck_name }}" ]; then
            echo "all_changed_files=$(find decks/${{ github.event.inputs.deck_name }} -name '*.svg' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          else
            echo "all_changed_files=$(find decks -name '*.svg' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          fi
          echo "any_changed=true" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert SVG to PDF
        if: steps.files-to-process.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.deck_name }}" ]; then
              svg_files=$(find decks/${{ github.event.inputs.deck_name }} -name '*.svg')
            else
              svg_files=$(find decks -name '*.svg')
            fi
          else
            svg_files="${{ steps.files-to-process.outputs.all_changed_files }}"
          fi
          
          for svg_file in $svg_files; do
            if [ -f "$svg_file" ] && [[ "$svg_file" == *.svg ]]; then
              filename=$(basename "$svg_file" .svg)
              # Get the QR code path (using the correct pattern)
              qr_path=$(dirname "$svg_file")/${filename%-output}-qr.png
              
              # Check if QR code exists
              if [ -f "$qr_path" ]; then
                # Convert QR code to base64
                qr_base64=$(base64 -w 0 "$qr_path")
                
                # Create a temporary SVG with embedded QR code
                temp_svg="/tmp/${filename}.svg"
                sed "s|https://blog.session.it/quiz/decks/devops-hero/questions/${filename%-output}-qr.png|data:image/png;base64,$qr_base64|g" "$svg_file" > "$temp_svg"
                
                docker run --rm \
                  -v "$PWD:/work" \
                  -v "/tmp:/tmp" \
                  -w /work \
                  ghcr.io/${{ github.repository }}/svg-to-pdf:latest \
                  rsvg-convert -f pdf \
                    -o "$(dirname "$svg_file")/${filename}.pdf" \
                    -w 416 \
                    -h 416 \
                    "$temp_svg"
                
                # Clean up temporary file
                rm "$temp_svg"
              else
                echo "Warning: QR code file not found: $qr_path"
                # Convert without QR code
                docker run --rm \
                  -v "$PWD:/work" \
                  -w /work \
                  ghcr.io/${{ github.repository }}/svg-to-pdf:latest \
                  rsvg-convert -f pdf \
                    -o "$(dirname "$svg_file")/${filename}.pdf" \
                    -w 416 \
                    -h 416 \
                    "$svg_file"
              fi
            fi
          done

      - name: Commit and push changes
        if: steps.files-to-process.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add decks/*.pdf
          git commit -m "Convert SVG to PDF" || exit 0
          git push origin HEAD:${{ github.ref }} 