name: Convert SVG to PDF

on:
  workflow_run:
    workflows: ["Convert YAML to SVG"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      deck_name:
        description: 'Name of the deck to process (e.g., "deck1"). Leave empty to process all decks.'
        required: false
        type: string

jobs:
  convert-svg:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout branches
        uses: ./.github/actions/checkout-branches
        with:
          deck_name: '${{ github.event.inputs.deck_name }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: '3.11'
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Convert SVG to PDF
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ./scripts/svg_to_pdf.sh "gh-pages/decks/${{ github.event.inputs.deck_name }}"
          else
            DECKS_PATHS=$(ls -d gh-pages/decks/*/)
            ./scripts/svg_to_pdf.sh $DECKS_PATHS
          fi
      - name: Commit and push changes
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: "Convert SVG to PDF"
          user-name: "maoo"
          user-email: "maoo@apache.org"
