name: Test SVG to PDF

on:
  push:
    paths:
      - 'svg-to-pdf/**'
      - '.github/workflows/test-svg-to-pdf.yml'
  pull_request:
    paths:
      - 'svg-to-pdf/**'
      - '.github/workflows/test-svg-to-pdf.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev librsvg2-dev
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          cd svg-to-pdf
          poetry install
          
      - name: Run tests
        run: |
          cd svg-to-pdf
          poetry run pytest
          
      - name: Run linting
        run: |
          cd svg-to-pdf
          poetry run flake8 svg_to_pdf tests
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./svg-to-pdf/coverage.xml
          flags: svg-to-pdf