name: Convert YAML to SVG

on:
  # QRs must be generated before SVGs
  workflow_run:
    workflows: ["QR Code Generator"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      deck_name:
        description: 'Name of the deck to process (e.g., "deck1"). Leave empty to process all decks.'
        required: false
        type: string

permissions:
  contents: write

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install
          
      - name: Generate SVG files
        run: |
          chmod +x scripts/yaml_to_svg.sh
          if [ -n "${{ github.event.inputs.deck_name }}" ]; then
            ./scripts/yaml_to_svg.sh manual "${{ github.event.inputs.deck_name }}"
          else
            # Get all deck names
            for deck in decks/*; do
              if [ -d "$deck" ]; then
                deck_name=$(basename "$deck")
                ./scripts/yaml_to_svg.sh manual "$deck_name"
              fi
            done
          fi

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add decks/**/*.svg
          git commit -m "Convert YAML to SVG" || exit 0
          git push origin gh-pages